config/routes.rb
Blog::Application.routes.draw do
	resources :categories, :except => :show
	
  resources :posts do
  	resources :comments, :only => [:create, :destroy]
  end
  
	resources :users do
  	post 'login', :on => :collection
	end
	
	match 'login' => 'users#index'
	match 'signup' => 'users#new'
	match 'logout' => 'users#logout'

 	root :to => 'users#index'

	match '*k', :to => 'errors#routing'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :posts
  
  before_destroy :assign_default_category
  
  validates :name, :presence => true, :uniqueness => true
  
  private
  
#  def move_to_default_category
    #FIX: This is the wrong way to assign default category. See my commented code below
#    self.posts.update_all("category_id = 1")
#  end
  
  def default_category
    @default_category ||= Category.find(1)
  end
  
  def assign_default_category
  	default_category
    default_category.posts << self.posts
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commenter
  
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :name, :title, :tags_attributes, :category_id, :user_id
  
  belongs_to :category
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :tags
  
  validates :name, :presence => true
  validates :title, :presence => true,
  									:length => {:minimum => 5}
  validates :description, :presence => true
  validates :category_id, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :password, :username, :password_confirmation
  
  before_create :hash_password
  
  validates :username, :presence => true, :uniqueness => true
  validates :password, :presence => true, 
  										 :length => {:minimum => 5}, 
  										 :confirmation => true
	  										 
  has_many :posts, :dependent => :destroy
  
  def self.authenticate(username, password)
  	User.find(:first, :conditions => ["username = ? and password = ?", username, Digest::SHA512.hexdigest(password)]) 
  end
  
  def hash_password
  	self.password = Digest::SHA512.hexdigest(self.password)
  end
end

app/controllers/application_controller.rb
require_dependency 'password'

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
		@default_category = Category.find(1).name
		respond_to do |format|
      format.html # index.html.erb
    end
	end

	def edit
		if Category.exists?(params[:id])
			@category = Category.find(params[:id])
		else
			render :file => "#{Rails.root}/public/recordnotfound.html", :layout => false
		end	
	end

	def new
		@category = Category.new
		
		respond_to do |format|
		  format.html
		end
	end
	
	def update
		@category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
	end
	
	def destroy
		@category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end
	end
	
	def create
		@category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
      else
        format.html { redirect_to new_category_path,  notice: 'Category cannot be empty!'}
      end
    end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    if @comment = @post.comments.create(params[:comment])
	    redirect_to post_path(@post)
	   else
	   	flash[:error] = "Error"
	   end
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	def routing
		render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:per_page => 5, :page => params[:page])

    respond_to do |format|
      format.html
    end
  end
  
  def show
  	if Post.exists?(params[:id])
	  	@post = Post.find(params[:id])
			respond_to do |format|
			  format.html
			  format.json { render json: @post }
			end
		else
			render :file => "#{Rails.root}/public/recordnotfound.html", :layout => false
		end
  end

  def new
    @post = Post.new
		@categories = Category.all
    respond_to do |format|
      format.html 
      format.json { render json: @post }
    end
  end

  def edit
		if Post.exists?(params[:id])
			@post = Post.find(params[:id])
		else
			render :file => "#{Rails.root}/public/recordnotfound.html", :layout => false
		end   
  end

  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		respond_to do |format|
			#session[:current_user] = nil
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
  
	def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
		
	def create
	  @user = User.new(params[:user])

	  respond_to do |format|
	    if @user.save
	    	session[:current_user] = @user.username
	    	session[:current_user_id] = @user.id
	      format.html { redirect_to posts_path, notice: 'You are successfully registered!' }
	      format.json { render json: posts_path, status: :created, location: posts_path }
	    else
	      format.html { render action: "new" }
	      format.json { render json: @user.errors, status: :unprocessable_entity }
	    end
	  end
	end
	
	def login
		respond_to do |format|
			if user = User.authenticate(params[:username], params[:password])
				session[:current_user] = user.username
				flash[:notice] = "You have logged in successfully!"
				format.html { redirect_to posts_path }
			else
				format.html { redirect_to login_path, notice: 'username or password is incorrect!'}
			end
		end
	end
	
	def logout
		session[:current_user] = nil
		redirect_to login_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
	<div>
			<div class="field">
				<%= f.label :name %><br />
				<%= f.text_field :name %>
			</div>
		
			<div class="actions">
				<%= f.submit %>
			</div>	
	</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>
<p><%= flash[:notice] %></p>
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Manage Categories</h1>

<p><%= flash[:notice] %></p>

<div>
	<table>
		<tr>
			<th>Categories</th>
			<th colspan="2">Actions</th>
		</tr>
		<% @categories.each do |category| %>
			<tr>
				<td><%= category.name %></td>
				<td><%= link_to "edit", edit_category_path(category) %></td>
				<% if category.id != 1 %>
					<td><%= link_to "destroy", category, confirm: "All posts under this category will be moved to default category(#{@default_category})!", method: :delete %></td>
				<% end %>
			</tr>
		<% end %>
	</table>
	<br/>
	<%= link_to 'New', new_category_path %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<p><%= flash[:notice] %></p>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "home", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = wrapper>
		<div class = content_wrapper>
			<div class = header>
				<div class = text> Blogging </div>
			</div>
	<br /> 
		<%= yield %>
		<div>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p><%= flash[:error] %></p>

  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :description %><br />
    <%= post_form.text_area :description, :rows => 10 %>
  </div>
	
	<div class = "categories">
		<%= post_form.label :category %><br />
		<%= post_form.select :category_id, Category.all.collect {|c| [ c.name, c.id ]}, :selected => 1%>
	</div>
   <br />
   
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>
 <br />

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div> <%= flash[:notice] %> </div>

<% if session[:current_user] %>
	<div>Hi <b><%= session[:current_user] %></b></div>
	<div> <%= link_to 'logout', logout_path %> </div>
<% else %>
	<div> <%= link_to 'login', login_path %> </div>
	<div> <%= link_to 'signup', signup_path %> </div>
<% end %>

<h1>Listing posts</h1>

<table class = "posts">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

	<% @posts.each do |post| %>
		<tr>
		  <td><%= post.name %></td>
		  <td><%= post.title %></td>
		  <td><%= post.description %></td>
		 	<td><%= post.category.name %></td>
		  <td><%= link_to 'Show', post %></td>			
		  <% if session[:current_user] %>
				<td><%= link_to 'Edit', edit_post_path(post) %></td>
				<td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
			<% end %>
		</tr>
	<% end %>	
</table>
	<br />
	<%= will_paginate @posts %>

<br />

<% if session[:current_user] %>
	<%= link_to 'New post', new_post_path %>
	<%= link_to 'Manage categories', categories_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"> <%= notice %> </p>

<p id="notice"> <%= flash[:error] %> </p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>

<p>
  <b>Category:</b>
  <%= @post.category.name %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
  
  <p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?', :method => :delete %>
	</p>
<% end %>

<h2>Add a comment:</h2>
<%= render "comments/form"%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_login_form.html.erb
<%= form_tag :action => "login" do %>
	<p><%= notice %></p>
	<table>
		<tr>
			<td><%=  label_tag(:username, "Username")  %></td>
			<td><%=  text_field_tag(:username) %></td>
		</tr>
		<tr>
			<td><%=  label_tag(:password, "Password")  %></td>
			<td><%=  password_field_tag(:password) %></td>
		</tr>
		<tr>
			<td> <%= submit_tag("Submit") %> </td>
		</tr>
	</table>
	<br />		
	<span> <%= link_to "Sign Up", signup_path %> </span>
	<span> <%= link_to "Visit", posts_path %> </span>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited you from being registered:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<table>
		<tr>
			<td><%=  f.label(:username, "Username")  %></td>
			<td><%=  f.text_field(:username) %></td>
		</tr>
		<tr>
			<td><%=  f.label(:password, "Password")  %></td>
			<td><%=  f.password_field(:password) %></td>
		</tr>
		<tr>
			<td><%=  f.label(:password_confirmation, "Confirm")  %></td>
			<td><%=  f.password_field(:password_confirmation) %></td>
		</tr>
		<tr>
			<td> <%= f.submit("Submit") %> </td>
		</tr>
	</table>
	<br />		
	<span> <%= link_to "Sign In", login_path %> </span>
	<span> <%= link_to "Visit", posts_path %> </span>
<% end %>

app/views/users/index.html.erb
<br /> <br /> <br /> <br /> <br />

<div class = login>
	<div class = head> Login </div>
	<%= render "login_form" %>
</div>

app/views/users/new.html.erb
<br /> <br /> <br /> <br /> <br />

<div class = login>
	<div class = head> Sign Up </div>
	<%= render 'signup_form'%>
</div>